package com.safevoice.backend.model.document;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * MongoDB document representing the encrypted data key for a tenant.
 * The data key is generated by AWS KMS, encrypted by AWS KMS, and stored here.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "tenant_keys")
public class TenantKey {

    @Id
    private String tenantId;

    private String encryptedDataKeyBase64;
}
