package com.safevoice.backend.service;

import com.safevoice.backend.dto.CaseActivityEvent;
import com.safevoice.backend.model.document.CaseMessage;
import com.safevoice.backend.model.document.CaseReport;
import com.safevoice.backend.model.embedded.EncryptedPayload;
import com.safevoice.backend.model.embedded.EvidenceAttachment;
import com.safevoice.backend.model.embedded.TimelineEvent;
import com.safevoice.backend.model.enums.audit.AuditActionType;
import com.safevoice.backend.model.enums.audit.AuditOutcome;
import com.safevoice.backend.model.enums.case_report.CaseStatus;
import com.safevoice.backend.repository.CaseMessageRepository;
import com.safevoice.backend.repository.CaseReportRepository;
import com.safevoice.backend.service.report.CaseReportService;
import com.safevoice.backend.websocket.CaseEventPublisher;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Service representing operations on CaseMessage chat channels.
 */
@Service
public class CaseMessageService {

    private final CaseMessageRepository caseMessageRepository;
    private final CaseReportRepository caseReportRepository;
    private final CaseReportService caseReportService;
    private final AuditLogService auditLogService;
    // Broadcasts the saved message live to anyone viewing the case.
    private final CaseEventPublisher caseEventPublisher;
    // Temporary only for local testing while running without AWS KMS. Keep false in production so
    // normal whistleblower plaintext messages are never accepted by default.
    @Value("${safevoice.allow-plaintext-intake-for-local-testing:false}")
    private boolean allowPlaintextIntakeForLocalTesting;

    @Autowired
    public CaseMessageService(
            CaseMessageRepository caseMessageRepository,
            CaseReportRepository caseReportRepository,
            CaseReportService caseReportService,
            AuditLogService auditLogService,
            CaseEventPublisher caseEventPublisher) {
        this.caseMessageRepository = caseMessageRepository;
        this.caseReportRepository = caseReportRepository;
        this.caseReportService = caseReportService;
        this.auditLogService = auditLogService;
        this.caseEventPublisher = caseEventPublisher;
    }

    /**
     * Post a new chat message inside a case channel.
     * Appends a timeline event and writes a MESSAGE_POSTED audit log.
     */
    public CaseMessage postMessage(
            String caseId,
            String text,
            EncryptedPayload encryptedText,
            String sender,
            String tenantId,
            String actorRole,
            String actorId,
            List<EvidenceAttachment> attachments) {

        if (tenantId == null || tenantId.trim().isEmpty()) {
            throw new IllegalArgumentException("Tenant ID context is required");
        }

        // A message must carry something: plain text, locked (encrypted) text, or at least one
        // file. This lets a reporter/handler send a file with no words, but blocks an empty message.
        boolean hasText = text != null && !text.trim().isEmpty();
        boolean hasEncrypted = encryptedText != null
                && encryptedText.getCiphertext() != null
                && !encryptedText.getCiphertext().isBlank();
        boolean hasFiles = attachments != null && !attachments.isEmpty();
        if (!hasText && !hasEncrypted && !hasFiles) {
            throw new IllegalArgumentException("A message must include text or at least one file");
        }

        // Verify parent case exists and belongs to the tenant
        CaseReport report = caseReportService.getById(caseId, tenantId);

        // Do not allow new messages/files on a closed case. The two-way channel is only open
        // while the case is being handled; once CLOSED the record is final (finality + a clean
        // retention lifecycle). Callers get a 409 they can show to the user.
        if (report.getStatus() == CaseStatus.CLOSED) {
            throw new ResponseStatusException(HttpStatus.CONFLICT,
                    "This case is closed, so no new messages or files can be added.");
        }

        // Decide how the words are stored, for EVERY case (HR grievances included now):
        //  - SYSTEM messages (e.g. the automatic 7-day acknowledgement): these are fixed,
        //    non-confidential notices generated by the server itself. There is no browser to
        //    lock them and no personal data to protect, so they are stored as plain text.
        //  - everything else: the words MUST arrive already locked in the sender's browser.
        //    Plain text is refused (unless the local-testing flag is on for dev). Files-only
        //    messages are always fine because a file has no readable words to leak here.
        boolean isSystem = "System".equalsIgnoreCase(sender);
        String storedText = null;
        EncryptedPayload storedEncrypted = null;
        if (isSystem) {
            storedText = text;
        } else if (hasEncrypted) {
            storedEncrypted = encryptedText;
        } else if (hasText && allowPlaintextIntakeForLocalTesting) {
            storedText = text; // local dev only
        } else if (hasText) {
            throw new IllegalArgumentException("Message text must be sent as client-side encrypted content.");
        }

        CaseMessage message = new CaseMessage();
        message.setTenantId(tenantId);
        message.setCaseId(caseId);
        message.setSender(sender);
        message.setText(storedText);
        message.setEncryptedText(storedEncrypted);
        message.setAttachments(attachments != null ? attachments : new ArrayList<>());
        message.setTimestamp(Instant.now());

        // Work out whether the writer is the reporter or a staff member. The public web
        // app labels reporter messages "Anonymous Whistleblower"; internal tools use
        // "Reporter". Either way we mark the message as already read by its own author.
        boolean fromReporter = sender != null
                && (sender.equalsIgnoreCase("Reporter")
                    || sender.toLowerCase().contains("whistleblower"));
        if (fromReporter) {
            message.setReadByReporter(true);
            message.setReadByAdmin(false);
        } else {
            message.setReadByReporter(false);
            message.setReadByAdmin(true);
        }

        CaseMessage saved = caseMessageRepository.save(message);

        // Append message event to parent case report timeline
        report.getTimeline().add(new TimelineEvent(
                new org.bson.types.ObjectId().toHexString(),
                "New Message",
                "Chat message posted by " + sender,
                Instant.now(),
                "message"
        ));
        caseReportRepository.save(report);

        // Record compliance audit log
        auditLogService.log(
                tenantId,
                actorRole,
                actorId,
                AuditActionType.MESSAGE_POSTED,
                caseId,
                AuditOutcome.RECORDED,
                null,
                saved.getId(),
                "Message posted inside case channel."
        );

        // Push the message live to anyone viewing this case (reporter + staff with it open).
        // Best-effort: the message is already saved, so a failed broadcast must not throw.
        caseEventPublisher.publishMessage(caseId, saved);

        // Also tell the whole tenant's staff that this case had activity, so their lists
        // reorder (most-recent first), unread badges update, and off-case staff get a
        // "new reply" notification — no matter which page they are on.
        caseEventPublisher.publishActivity(tenantId, CaseActivityEvent.builder()
                .caseId(caseId)
                .caseReference(report.getCaseReference())
                .sender(sender)
                .fromReporter(fromReporter)
                .at(saved.getTimestamp())
                .build());

        return saved;
    }

    /**
     * Retrieves all chat messages for a case report.
     * Enforces tenant isolation.
     */
    public List<CaseMessage> getMessages(String caseId, String tenantId) {
        // Enforce validation by fetching case details first (triggers NoSuchElement if invalid/cross-tenant)
        caseReportService.getById(caseId, tenantId);
        return caseMessageRepository.findAllByTenantIdAndCaseIdOrderByTimestampAsc(tenantId, caseId);
    }

    /**
     * Find ONE attachment on ONE message of a case, after checking it really belongs to this
     * tenant and case. Used by the download endpoints so a caller can only ever reach a file
     * that is part of a case they are allowed to see. Throws if anything does not line up.
     */
    public EvidenceAttachment getMessageAttachment(
            String caseId, String messageId, String attachmentId, String tenantId) {
        // Tenant + case guard (throws if the case is not this tenant's).
        caseReportService.getById(caseId, tenantId);

        CaseMessage message = caseMessageRepository.findById(messageId)
                .orElseThrow(() -> new IllegalArgumentException("Message not found"));

        // The message must belong to the SAME tenant and case as the request path.
        if (!tenantId.equals(message.getTenantId()) || !caseId.equals(message.getCaseId())) {
            throw new IllegalArgumentException("Message does not belong to this case");
        }

        return message.getAttachments().stream()
                .filter(a -> attachmentId.equals(a.getId()))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("Attachment not found in this message"));
    }
}
